ALTER TABLE sbd.address
    ADD CONSTRAINT pk_address_id PRIMARY KEY (id),
    ALTER id SET DEFAULT (UUID()),
    MODIFY street VARCHAR(36) NOT NULL,
    MODIFY house_number INT NOT NULL,
    MODIFY rt INT NOT NULL,
    MODIFY rw INT NOT NULL,
    MODIFY village VARCHAR(255) NOT NULL,
    MODIFY district VARCHAR(255) NOT NULL,
    MODIFY city VARCHAR(255) NOT NULL,
    MODIFY province VARCHAR(255) NOT NULL,
    MODIFY postal_code VARCHAR(5) NOT NULL;

ALTER TABLE sbd.address
    ALTER id SET DEFAULT (UUID());